In [1]:
import httpx
import pandas as pd
from pathlib import Path
import shutil
import os

In [2]:
ROOT = Path.cwd().parent

BRONZE = ROOT / "data" / "bronze"

In [ ]:
URL = "https://api.openf1.org/v1/"

driver = httpx.get(URL + "drivers")
session_result = httpx.get(URL + "session_result")
meetings = httpx.get(URL + "meetings")
sessions = httpx.get(URL + "sessions")
weather = httpx.get(URL + "weather")
stints = httpx.get(URL + "stints")
laps = httpx.get(URL + "laps", timeout=None)
pits = httpx.get(URL + "pit")
race_control = httpx.get(URL +"race_control")
champ_driver = httpx.get(URL + "championship_drivers")

In [17]:
bd_drivers = pd.DataFrame(driver.json())
bd_sessions = pd.DataFrame(sessions.json())
bd_meetings = pd.DataFrame(meetings.json())
bd_weather = pd.DataFrame(weather.json())
bd_stints = pd.DataFrame(stints.json())
bd_laps = pd.DataFrame(laps.json())
bd_pits = pd.DataFrame(pits.json())
bd_race_control = pd.DataFrame(race_control.json())
bd_champ_driver = pd.DataFrame(champ_driver.json())

In [18]:
bd_drivers.head()

,meeting_key,session_key,driver_number,broadcast_name,full_name,name_acronym,team_name,team_colour,first_name,last_name,headshot_url,country_code
0,1140,7763,1,M VERSTAPPEN,Max VERSTAPPEN,VER,Red Bull Racing,3671C6,Max,Verstappen,https://www.formula1.com/content/dam/fom-websi...,NED
1,1140,7763,2,L SARGEANT,Logan SARGEANT,SAR,Williams,37BEDD,Logan,Sargeant,https://www.formula1.com/content/dam/fom-websi...,USA
2,1140,7763,4,L NORRIS,Lando NORRIS,NOR,McLaren,F58020,Lando,Norris,https://www.formula1.com/content/dam/fom-websi...,GBR
3,1140,7763,10,P GASLY,Pierre GASLY,GAS,Alpine,2293D1,Pierre,Gasly,https://www.formula1.com/content/dam/fom-websi...,FRA
4,1140,7763,11,S PEREZ,Sergio PEREZ,PER,Red Bull Racing,3671C6,Sergio,Perez,https://www.formula1.com/content/dam/fom-websi...,MEX

In [ ]:
bd_sessions.head()

In [ ]:
bd_meetings.head()

In [ ]:
bd_weather.head()

In [ ]:
bd_stints.head()

In [ ]:
bd_laps.head()

In [ ]:
bd_pits.head()

In [ ]:
bd_race_control.head()

In [ ]:
bd_champ_driver.head()

In [ ]:
bd_drivers.to_parquet(BRONZE / "bd_pilotos.parquet", index=False)
bd_sessions.to_parquet(BRONZE / "bd_sessions.parquet", index=False)
bd_meetings.to_parquet(BRONZE / "bd_metings.parquet", index=False)
bd_weather.to_parquet(BRONZE / "bd_weather.parquet", index=False)
bd_stints.to_parquet(BRONZE / "bd_stints.parquet", index=False)
bd_laps.to_parquet(BRONZE / "bd_laps.parquet", index=False)
bd_pits.to_parquet(BRONZE / "bd_pits.parquet", index=False) 
bd_race_control.to_parquet(BRONZE / "bd_race_control.parquet", index=False)
bd_champ_driver.to_parquet(BRONZE / "bd_champ_driver.parquet",index=False)

In [20]:
def connection_api(endpoint):
    #conexion a la API
    endpoint_api = httpx.get(URL + endpoint)
    bd_endpoint = pd.DataFrame(endpoint_api.json())
    bd_endpoint.to_parquet(BRONZE / f"bd_{endpoint}.parquet", index=False)
    return bd_endpoint.head()

In [22]:
connection_api("pit")

,date,session_key,stop_duration,meeting_key,driver_number,lap_number,lane_duration,pit_duration
0,2023-06-02T11:30:03.731000+00:00,9095,NaN,1211,14,1,NaN,NaN
1,2023-06-02T11:30:07.637000+00:00,9095,NaN,1211,11,1,NaN,NaN
2,2023-06-02T11:30:10.059000+00:00,9095,NaN,1211,18,1,NaN,NaN
3,2023-06-02T11:30:11.903000+00:00,9095,NaN,1211,21,1,NaN,NaN
4,2023-06-02T11:30:14.028000+00:00,9095,NaN,1211,31,1,NaN,NaN